name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name:
      run: |
        export ARDUINO_VERSION=1.8.7
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install curl python git
        pip install pyserial
    - name: Download Arduino ${ARDUINO_VERSION} portable version
      run: |
        curl -O https://downloads.arduino.cc/arduino-${ARDUINO_VERSION}-linux64.tar.xz
    - name: Unpack the contents of the Arduino package
      run: tar xvfJ arduino-${ARDUINO_VERSION}-linux64.tar.xz
    - name: Install Arduino boards and packages required
      run: |
        mv Phoenix_* arduino-1.8.7/libraries/
        mv ServoEx arduino-1.8.7/libraries/
        mkdir arduino-1.8.7/libraries/Phoenix
        mv Phoenix/Phoenix.h arduino-1.8.7/libraries/Phoenix/
        mv Phoenix/Phoenix_Code.h arduino-1.8.7/libraries/Phoenix/
        ${PWD}/arduino-1.8.7/arduino --pref "boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json" --save-prefs
        ${PWD}/arduino-1.8.7/arduino --install-boards esp32:esp32
        git clone https://github.com/m5stack/M5StickC.git arduino-1.8.7/libraries/M5StickC
        git clone https://github.com/jvpernis/esp32-ps3.git arduino-1.8.7/libraries/esp32-ps3
        cd arduino-1.8.7/libraries/esp32-ps3
        git checkout develop
        cd ../../../
        ls -la
        echo ${PWD}
      shell: bash
    - name: arduino folder contents
      run: |
        cd arduino-1.8.7
        echo ${PWD}
        ls -la
      shell: bash
    - name: arduino library folder contents
      run: |
        cd arduino-1.8.7/libraries/
        echo ${PWD}
        ls -la
      shell: bash
    - name: Compile project
      run: |
        ${PWD}/arduino-1.8.7/arduino --board esp32:esp32:m5stick-c --verify Phoenix/AliPhoenix_PS3_Maestro_M5StickC/AliPhoenix_PS3_Maestro_M5StickC.ino
      shell: bash
