name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arduino: [1.8.9, 1.8.10]
    env: 
      ARDUINO_VERSION: 1.8.10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install curl python git
        pip install pyserial
    - name: Download Arduino ${{ matrix.arduino }} portable version
      run: |
        curl -O https://downloads.arduino.cc/arduino-${{ matrix.arduino }}-linux64.tar.xz
    - name: Unpack the contents of the Arduino package
      run: tar xvfJ arduino-${{ matrix.arduino }}-linux64.tar.xz
    - name: Install Arduino boards required
      run: |
        ${PWD}/arduino-${{ matrix.arduino }}/arduino --pref "boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json" --save-prefs
        ${PWD}/arduino-${{ matrix.arduino }}/arduino --install-boards esp32:esp32
      shell: bash
    - name: Set up the Phoenix library
      run: |
        mv Phoenix_* arduino-${{ matrix.arduino }}/libraries/
        mv ServoEx arduino-${{ matrix.arduino }}/libraries/
        mkdir arduino-${{ matrix.arduino }}/libraries/Phoenix
        mv Phoenix/Phoenix.h arduino-${{ matrix.arduino }}/libraries/Phoenix/
        mv Phoenix/Phoenix_Code.h arduino-${{ matrix.arduino }}/libraries/Phoenix/
    - name: Install Phoenix dependency libraries
      run: |
        git clone https://github.com/m5stack/M5StickC.git arduino-${{ matrix.arduino }}/libraries/M5StickC
        git clone https://github.com/jvpernis/esp32-ps3.git arduino-${{ matrix.arduino }}/libraries/esp32-ps3
        cd arduino-${{ matrix.arduino }}/libraries/esp32-ps3
        git checkout develop
      shell: bash
    - name: Compile project
      run: |
        ${PWD}/arduino-${{ matrix.arduino }}/arduino --board esp32:esp32:m5stick-c --verify Phoenix/AliPhoenix_PS3_Maestro_M5StickC/AliPhoenix_PS3_Maestro_M5StickC.ino
      shell: bash
